// Auto-generated component registry
// Do not edit manually - run 'bun run generate-components'

import type { App } from 'vue';

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "./ui/accordion";
import { Alert, AlertAction, AlertDescription, AlertTitle } from "./ui/alert";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogMedia, AlertDialogTitle, AlertDialogTrigger } from "./ui/alert-dialog";
import { AspectRatio } from "./ui/aspect-ratio";
import { Avatar, AvatarBadge, AvatarFallback, AvatarGroup, AvatarGroupCount, AvatarImage } from "./ui/avatar";
import { Badge } from "./ui/badge";
import { Breadcrumb, BreadcrumbEllipsis, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "./ui/breadcrumb";
import { Button } from "./ui/button";
import { ButtonGroup, ButtonGroupSeparator, ButtonGroupText } from "./ui/button-group";
import { Calendar, CalendarCell, CalendarCellTrigger, CalendarGrid, CalendarGridBody, CalendarGridHead, CalendarGridRow, CalendarHeadCell, CalendarHeader, CalendarHeading, CalendarNextButton, CalendarPrevButton } from "./ui/calendar";
import { Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "./ui/card";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "./ui/carousel";
import { ChartContainer, ChartLegendContent, ChartTooltipContent } from "./ui/chart";
import { Checkbox } from "./ui/checkbox";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "./ui/collapsible";
import { Combobox, ComboboxAnchor, ComboboxEmpty, ComboboxGroup, ComboboxInput, ComboboxItem, ComboboxItemIndicator, ComboboxList, ComboboxSeparator, ComboboxTrigger, ComboboxViewport } from "./ui/combobox";
import { Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut } from "./ui/command";
import { ContextMenu, ContextMenuCheckboxItem, ContextMenuContent, ContextMenuGroup, ContextMenuItem, ContextMenuLabel, ContextMenuRadioGroup, ContextMenuRadioItem, ContextMenuSeparator, ContextMenuShortcut, ContextMenuSub, ContextMenuSubContent, ContextMenuSubTrigger, ContextMenuTrigger } from "./ui/context-menu";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogOverlay, DialogScrollContent, DialogTitle, DialogTrigger } from "./ui/dialog";
import { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerOverlay, DrawerTitle, DrawerTrigger } from "./ui/drawer";
import { DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from "./ui/dropdown-menu";
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "./ui/empty";
import { Field, FieldContent, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldLegend, FieldSeparator, FieldSet, FieldTitle } from "./ui/field";
import { FormControl, FormDescription, FormItem, FormLabel, FormMessage } from "./ui/form";
import { HoverCard, HoverCardContent, HoverCardTrigger } from "./ui/hover-card";
import { Input } from "./ui/input";
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput, InputGroupText, InputGroupTextarea } from "./ui/input-group";
import { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from "./ui/input-otp";
import { Item, ItemActions, ItemContent, ItemDescription, ItemFooter, ItemGroup, ItemHeader, ItemMedia, ItemSeparator, ItemTitle } from "./ui/item";
import { Kbd, KbdGroup } from "./ui/kbd";
import { Label } from "./ui/label";
import { Menubar, MenubarCheckboxItem, MenubarContent, MenubarGroup, MenubarItem, MenubarLabel, MenubarMenu, MenubarRadioGroup, MenubarRadioItem, MenubarSeparator, MenubarShortcut, MenubarSub, MenubarSubContent, MenubarSubTrigger, MenubarTrigger } from "./ui/menubar";
import { NativeSelect, NativeSelectOptGroup, NativeSelectOption } from "./ui/native-select";
import { NavigationMenu, NavigationMenuContent, NavigationMenuIndicator, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, NavigationMenuViewport } from "./ui/navigation-menu";
import { NumberField, NumberFieldContent, NumberFieldDecrement, NumberFieldIncrement, NumberFieldInput } from "./ui/number-field";
import { Pagination, PaginationContent, PaginationEllipsis, PaginationFirst, PaginationItem, PaginationLast, PaginationLink, PaginationNext, PaginationPrevious } from "./ui/pagination";
import { PinInput, PinInputGroup, PinInputSeparator, PinInputSlot } from "./ui/pin-input";
import { Popover, PopoverAnchor, PopoverContent, PopoverDescription, PopoverHeader, PopoverTitle, PopoverTrigger } from "./ui/popover";
import { Progress } from "./ui/progress";
import { RadioGroup, RadioGroupItem } from "./ui/radio-group";
import { RangeCalendar, RangeCalendarCell, RangeCalendarCellTrigger, RangeCalendarGrid, RangeCalendarGridBody, RangeCalendarGridHead, RangeCalendarGridRow, RangeCalendarHeadCell, RangeCalendarHeader, RangeCalendarHeading, RangeCalendarNextButton, RangeCalendarPrevButton } from "./ui/range-calendar";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "./ui/resizable";
import { ScrollArea, ScrollBar } from "./ui/scroll-area";
import { Select, SelectContent, SelectGroup, SelectItem, SelectItemText, SelectLabel, SelectScrollDownButton, SelectScrollUpButton, SelectSeparator, SelectTrigger, SelectValue } from "./ui/select";
import { Separator } from "./ui/separator";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from "./ui/sheet";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupAction, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInput, SidebarInset, SidebarMenu, SidebarMenuAction, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarMenuSkeleton, SidebarMenuSub, SidebarMenuSubButton, SidebarMenuSubItem, SidebarProvider, SidebarRail, SidebarSeparator, SidebarTrigger } from "./ui/sidebar";
import { Skeleton } from "./ui/skeleton";
import { Slider } from "./ui/slider";
import { Toaster } from "./ui/sonner";
import { Spinner } from "./ui/spinner";
import { Stepper, StepperDescription, StepperIndicator, StepperItem, StepperSeparator, StepperTitle, StepperTrigger } from "./ui/stepper";
import { Switch } from "./ui/switch";
import { Table, TableBody, TableCaption, TableCell, TableEmpty, TableFooter, TableHead, TableHeader, TableRow } from "./ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { TagsInput, TagsInputInput, TagsInputItem, TagsInputItemDelete, TagsInputItemText } from "./ui/tags-input";
import { Textarea } from "./ui/textarea";
import { Toggle } from "./ui/toggle";
import { ToggleGroup, ToggleGroupItem } from "./ui/toggle-group";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./ui/tooltip";

export function registerComponents(app: App): void {
  app.component('Accordion', Accordion);
  app.component('AccordionContent', AccordionContent);
  app.component('AccordionItem', AccordionItem);
  app.component('AccordionTrigger', AccordionTrigger);
  app.component('Alert', Alert);
  app.component('AlertAction', AlertAction);
  app.component('AlertDescription', AlertDescription);
  app.component('AlertTitle', AlertTitle);
  app.component('AlertDialog', AlertDialog);
  app.component('AlertDialogAction', AlertDialogAction);
  app.component('AlertDialogCancel', AlertDialogCancel);
  app.component('AlertDialogContent', AlertDialogContent);
  app.component('AlertDialogDescription', AlertDialogDescription);
  app.component('AlertDialogFooter', AlertDialogFooter);
  app.component('AlertDialogHeader', AlertDialogHeader);
  app.component('AlertDialogMedia', AlertDialogMedia);
  app.component('AlertDialogTitle', AlertDialogTitle);
  app.component('AlertDialogTrigger', AlertDialogTrigger);
  app.component('AspectRatio', AspectRatio);
  app.component('Avatar', Avatar);
  app.component('AvatarBadge', AvatarBadge);
  app.component('AvatarFallback', AvatarFallback);
  app.component('AvatarGroup', AvatarGroup);
  app.component('AvatarGroupCount', AvatarGroupCount);
  app.component('AvatarImage', AvatarImage);
  app.component('Badge', Badge);
  app.component('Breadcrumb', Breadcrumb);
  app.component('BreadcrumbEllipsis', BreadcrumbEllipsis);
  app.component('BreadcrumbItem', BreadcrumbItem);
  app.component('BreadcrumbLink', BreadcrumbLink);
  app.component('BreadcrumbList', BreadcrumbList);
  app.component('BreadcrumbPage', BreadcrumbPage);
  app.component('BreadcrumbSeparator', BreadcrumbSeparator);
  app.component('Button', Button);
  app.component('ButtonGroup', ButtonGroup);
  app.component('ButtonGroupSeparator', ButtonGroupSeparator);
  app.component('ButtonGroupText', ButtonGroupText);
  app.component('Calendar', Calendar);
  app.component('CalendarCell', CalendarCell);
  app.component('CalendarCellTrigger', CalendarCellTrigger);
  app.component('CalendarGrid', CalendarGrid);
  app.component('CalendarGridBody', CalendarGridBody);
  app.component('CalendarGridHead', CalendarGridHead);
  app.component('CalendarGridRow', CalendarGridRow);
  app.component('CalendarHeadCell', CalendarHeadCell);
  app.component('CalendarHeader', CalendarHeader);
  app.component('CalendarHeading', CalendarHeading);
  app.component('CalendarNextButton', CalendarNextButton);
  app.component('CalendarPrevButton', CalendarPrevButton);
  app.component('Card', Card);
  app.component('CardAction', CardAction);
  app.component('CardContent', CardContent);
  app.component('CardDescription', CardDescription);
  app.component('CardFooter', CardFooter);
  app.component('CardHeader', CardHeader);
  app.component('CardTitle', CardTitle);
  app.component('Carousel', Carousel);
  app.component('CarouselContent', CarouselContent);
  app.component('CarouselItem', CarouselItem);
  app.component('CarouselNext', CarouselNext);
  app.component('CarouselPrevious', CarouselPrevious);
  app.component('ChartContainer', ChartContainer);
  app.component('ChartLegendContent', ChartLegendContent);
  app.component('ChartTooltipContent', ChartTooltipContent);
  app.component('Checkbox', Checkbox);
  app.component('Collapsible', Collapsible);
  app.component('CollapsibleContent', CollapsibleContent);
  app.component('CollapsibleTrigger', CollapsibleTrigger);
  app.component('Combobox', Combobox);
  app.component('ComboboxAnchor', ComboboxAnchor);
  app.component('ComboboxEmpty', ComboboxEmpty);
  app.component('ComboboxGroup', ComboboxGroup);
  app.component('ComboboxInput', ComboboxInput);
  app.component('ComboboxItem', ComboboxItem);
  app.component('ComboboxItemIndicator', ComboboxItemIndicator);
  app.component('ComboboxList', ComboboxList);
  app.component('ComboboxSeparator', ComboboxSeparator);
  app.component('ComboboxTrigger', ComboboxTrigger);
  app.component('ComboboxViewport', ComboboxViewport);
  app.component('Command', Command);
  app.component('CommandDialog', CommandDialog);
  app.component('CommandEmpty', CommandEmpty);
  app.component('CommandGroup', CommandGroup);
  app.component('CommandInput', CommandInput);
  app.component('CommandItem', CommandItem);
  app.component('CommandList', CommandList);
  app.component('CommandSeparator', CommandSeparator);
  app.component('CommandShortcut', CommandShortcut);
  app.component('ContextMenu', ContextMenu);
  app.component('ContextMenuCheckboxItem', ContextMenuCheckboxItem);
  app.component('ContextMenuContent', ContextMenuContent);
  app.component('ContextMenuGroup', ContextMenuGroup);
  app.component('ContextMenuItem', ContextMenuItem);
  app.component('ContextMenuLabel', ContextMenuLabel);
  app.component('ContextMenuRadioGroup', ContextMenuRadioGroup);
  app.component('ContextMenuRadioItem', ContextMenuRadioItem);
  app.component('ContextMenuSeparator', ContextMenuSeparator);
  app.component('ContextMenuShortcut', ContextMenuShortcut);
  app.component('ContextMenuSub', ContextMenuSub);
  app.component('ContextMenuSubContent', ContextMenuSubContent);
  app.component('ContextMenuSubTrigger', ContextMenuSubTrigger);
  app.component('ContextMenuTrigger', ContextMenuTrigger);
  app.component('Dialog', Dialog);
  app.component('DialogClose', DialogClose);
  app.component('DialogContent', DialogContent);
  app.component('DialogDescription', DialogDescription);
  app.component('DialogFooter', DialogFooter);
  app.component('DialogHeader', DialogHeader);
  app.component('DialogOverlay', DialogOverlay);
  app.component('DialogScrollContent', DialogScrollContent);
  app.component('DialogTitle', DialogTitle);
  app.component('DialogTrigger', DialogTrigger);
  app.component('Drawer', Drawer);
  app.component('DrawerClose', DrawerClose);
  app.component('DrawerContent', DrawerContent);
  app.component('DrawerDescription', DrawerDescription);
  app.component('DrawerFooter', DrawerFooter);
  app.component('DrawerHeader', DrawerHeader);
  app.component('DrawerOverlay', DrawerOverlay);
  app.component('DrawerTitle', DrawerTitle);
  app.component('DrawerTrigger', DrawerTrigger);
  app.component('DropdownMenu', DropdownMenu);
  app.component('DropdownMenuCheckboxItem', DropdownMenuCheckboxItem);
  app.component('DropdownMenuContent', DropdownMenuContent);
  app.component('DropdownMenuGroup', DropdownMenuGroup);
  app.component('DropdownMenuItem', DropdownMenuItem);
  app.component('DropdownMenuLabel', DropdownMenuLabel);
  app.component('DropdownMenuRadioGroup', DropdownMenuRadioGroup);
  app.component('DropdownMenuRadioItem', DropdownMenuRadioItem);
  app.component('DropdownMenuSeparator', DropdownMenuSeparator);
  app.component('DropdownMenuShortcut', DropdownMenuShortcut);
  app.component('DropdownMenuSub', DropdownMenuSub);
  app.component('DropdownMenuSubContent', DropdownMenuSubContent);
  app.component('DropdownMenuSubTrigger', DropdownMenuSubTrigger);
  app.component('DropdownMenuTrigger', DropdownMenuTrigger);
  app.component('Empty', Empty);
  app.component('EmptyContent', EmptyContent);
  app.component('EmptyDescription', EmptyDescription);
  app.component('EmptyHeader', EmptyHeader);
  app.component('EmptyMedia', EmptyMedia);
  app.component('EmptyTitle', EmptyTitle);
  app.component('Field', Field);
  app.component('FieldContent', FieldContent);
  app.component('FieldDescription', FieldDescription);
  app.component('FieldError', FieldError);
  app.component('FieldGroup', FieldGroup);
  app.component('FieldLabel', FieldLabel);
  app.component('FieldLegend', FieldLegend);
  app.component('FieldSeparator', FieldSeparator);
  app.component('FieldSet', FieldSet);
  app.component('FieldTitle', FieldTitle);
  app.component('FormControl', FormControl);
  app.component('FormDescription', FormDescription);
  app.component('FormItem', FormItem);
  app.component('FormLabel', FormLabel);
  app.component('FormMessage', FormMessage);
  app.component('HoverCard', HoverCard);
  app.component('HoverCardContent', HoverCardContent);
  app.component('HoverCardTrigger', HoverCardTrigger);
  app.component('Input', Input);
  app.component('InputGroup', InputGroup);
  app.component('InputGroupAddon', InputGroupAddon);
  app.component('InputGroupButton', InputGroupButton);
  app.component('InputGroupInput', InputGroupInput);
  app.component('InputGroupText', InputGroupText);
  app.component('InputGroupTextarea', InputGroupTextarea);
  app.component('InputOTP', InputOTP);
  app.component('InputOTPGroup', InputOTPGroup);
  app.component('InputOTPSeparator', InputOTPSeparator);
  app.component('InputOTPSlot', InputOTPSlot);
  app.component('Item', Item);
  app.component('ItemActions', ItemActions);
  app.component('ItemContent', ItemContent);
  app.component('ItemDescription', ItemDescription);
  app.component('ItemFooter', ItemFooter);
  app.component('ItemGroup', ItemGroup);
  app.component('ItemHeader', ItemHeader);
  app.component('ItemMedia', ItemMedia);
  app.component('ItemSeparator', ItemSeparator);
  app.component('ItemTitle', ItemTitle);
  app.component('Kbd', Kbd);
  app.component('KbdGroup', KbdGroup);
  app.component('Label', Label);
  app.component('Menubar', Menubar);
  app.component('MenubarCheckboxItem', MenubarCheckboxItem);
  app.component('MenubarContent', MenubarContent);
  app.component('MenubarGroup', MenubarGroup);
  app.component('MenubarItem', MenubarItem);
  app.component('MenubarLabel', MenubarLabel);
  app.component('MenubarMenu', MenubarMenu);
  app.component('MenubarRadioGroup', MenubarRadioGroup);
  app.component('MenubarRadioItem', MenubarRadioItem);
  app.component('MenubarSeparator', MenubarSeparator);
  app.component('MenubarShortcut', MenubarShortcut);
  app.component('MenubarSub', MenubarSub);
  app.component('MenubarSubContent', MenubarSubContent);
  app.component('MenubarSubTrigger', MenubarSubTrigger);
  app.component('MenubarTrigger', MenubarTrigger);
  app.component('NativeSelect', NativeSelect);
  app.component('NativeSelectOptGroup', NativeSelectOptGroup);
  app.component('NativeSelectOption', NativeSelectOption);
  app.component('NavigationMenu', NavigationMenu);
  app.component('NavigationMenuContent', NavigationMenuContent);
  app.component('NavigationMenuIndicator', NavigationMenuIndicator);
  app.component('NavigationMenuItem', NavigationMenuItem);
  app.component('NavigationMenuLink', NavigationMenuLink);
  app.component('NavigationMenuList', NavigationMenuList);
  app.component('NavigationMenuTrigger', NavigationMenuTrigger);
  app.component('NavigationMenuViewport', NavigationMenuViewport);
  app.component('NumberField', NumberField);
  app.component('NumberFieldContent', NumberFieldContent);
  app.component('NumberFieldDecrement', NumberFieldDecrement);
  app.component('NumberFieldIncrement', NumberFieldIncrement);
  app.component('NumberFieldInput', NumberFieldInput);
  app.component('Pagination', Pagination);
  app.component('PaginationContent', PaginationContent);
  app.component('PaginationEllipsis', PaginationEllipsis);
  app.component('PaginationFirst', PaginationFirst);
  app.component('PaginationItem', PaginationItem);
  app.component('PaginationLast', PaginationLast);
  app.component('PaginationLink', PaginationLink);
  app.component('PaginationNext', PaginationNext);
  app.component('PaginationPrevious', PaginationPrevious);
  app.component('PinInput', PinInput);
  app.component('PinInputGroup', PinInputGroup);
  app.component('PinInputSeparator', PinInputSeparator);
  app.component('PinInputSlot', PinInputSlot);
  app.component('Popover', Popover);
  app.component('PopoverAnchor', PopoverAnchor);
  app.component('PopoverContent', PopoverContent);
  app.component('PopoverDescription', PopoverDescription);
  app.component('PopoverHeader', PopoverHeader);
  app.component('PopoverTitle', PopoverTitle);
  app.component('PopoverTrigger', PopoverTrigger);
  app.component('Progress', Progress);
  app.component('RadioGroup', RadioGroup);
  app.component('RadioGroupItem', RadioGroupItem);
  app.component('RangeCalendar', RangeCalendar);
  app.component('RangeCalendarCell', RangeCalendarCell);
  app.component('RangeCalendarCellTrigger', RangeCalendarCellTrigger);
  app.component('RangeCalendarGrid', RangeCalendarGrid);
  app.component('RangeCalendarGridBody', RangeCalendarGridBody);
  app.component('RangeCalendarGridHead', RangeCalendarGridHead);
  app.component('RangeCalendarGridRow', RangeCalendarGridRow);
  app.component('RangeCalendarHeadCell', RangeCalendarHeadCell);
  app.component('RangeCalendarHeader', RangeCalendarHeader);
  app.component('RangeCalendarHeading', RangeCalendarHeading);
  app.component('RangeCalendarNextButton', RangeCalendarNextButton);
  app.component('RangeCalendarPrevButton', RangeCalendarPrevButton);
  app.component('ResizableHandle', ResizableHandle);
  app.component('ResizablePanel', ResizablePanel);
  app.component('ResizablePanelGroup', ResizablePanelGroup);
  app.component('ScrollArea', ScrollArea);
  app.component('ScrollBar', ScrollBar);
  app.component('Select', Select);
  app.component('SelectContent', SelectContent);
  app.component('SelectGroup', SelectGroup);
  app.component('SelectItem', SelectItem);
  app.component('SelectItemText', SelectItemText);
  app.component('SelectLabel', SelectLabel);
  app.component('SelectScrollDownButton', SelectScrollDownButton);
  app.component('SelectScrollUpButton', SelectScrollUpButton);
  app.component('SelectSeparator', SelectSeparator);
  app.component('SelectTrigger', SelectTrigger);
  app.component('SelectValue', SelectValue);
  app.component('Separator', Separator);
  app.component('Sheet', Sheet);
  app.component('SheetClose', SheetClose);
  app.component('SheetContent', SheetContent);
  app.component('SheetDescription', SheetDescription);
  app.component('SheetFooter', SheetFooter);
  app.component('SheetHeader', SheetHeader);
  app.component('SheetTitle', SheetTitle);
  app.component('SheetTrigger', SheetTrigger);
  app.component('Sidebar', Sidebar);
  app.component('SidebarContent', SidebarContent);
  app.component('SidebarFooter', SidebarFooter);
  app.component('SidebarGroup', SidebarGroup);
  app.component('SidebarGroupAction', SidebarGroupAction);
  app.component('SidebarGroupContent', SidebarGroupContent);
  app.component('SidebarGroupLabel', SidebarGroupLabel);
  app.component('SidebarHeader', SidebarHeader);
  app.component('SidebarInput', SidebarInput);
  app.component('SidebarInset', SidebarInset);
  app.component('SidebarMenu', SidebarMenu);
  app.component('SidebarMenuAction', SidebarMenuAction);
  app.component('SidebarMenuBadge', SidebarMenuBadge);
  app.component('SidebarMenuButton', SidebarMenuButton);
  app.component('SidebarMenuItem', SidebarMenuItem);
  app.component('SidebarMenuSkeleton', SidebarMenuSkeleton);
  app.component('SidebarMenuSub', SidebarMenuSub);
  app.component('SidebarMenuSubButton', SidebarMenuSubButton);
  app.component('SidebarMenuSubItem', SidebarMenuSubItem);
  app.component('SidebarProvider', SidebarProvider);
  app.component('SidebarRail', SidebarRail);
  app.component('SidebarSeparator', SidebarSeparator);
  app.component('SidebarTrigger', SidebarTrigger);
  app.component('Skeleton', Skeleton);
  app.component('Slider', Slider);
  app.component('Toaster', Toaster);
  app.component('Spinner', Spinner);
  app.component('Stepper', Stepper);
  app.component('StepperDescription', StepperDescription);
  app.component('StepperIndicator', StepperIndicator);
  app.component('StepperItem', StepperItem);
  app.component('StepperSeparator', StepperSeparator);
  app.component('StepperTitle', StepperTitle);
  app.component('StepperTrigger', StepperTrigger);
  app.component('Switch', Switch);
  app.component('Table', Table);
  app.component('TableBody', TableBody);
  app.component('TableCaption', TableCaption);
  app.component('TableCell', TableCell);
  app.component('TableEmpty', TableEmpty);
  app.component('TableFooter', TableFooter);
  app.component('TableHead', TableHead);
  app.component('TableHeader', TableHeader);
  app.component('TableRow', TableRow);
  app.component('Tabs', Tabs);
  app.component('TabsContent', TabsContent);
  app.component('TabsList', TabsList);
  app.component('TabsTrigger', TabsTrigger);
  app.component('TagsInput', TagsInput);
  app.component('TagsInputInput', TagsInputInput);
  app.component('TagsInputItem', TagsInputItem);
  app.component('TagsInputItemDelete', TagsInputItemDelete);
  app.component('TagsInputItemText', TagsInputItemText);
  app.component('Textarea', Textarea);
  app.component('Toggle', Toggle);
  app.component('ToggleGroup', ToggleGroup);
  app.component('ToggleGroupItem', ToggleGroupItem);
  app.component('Tooltip', Tooltip);
  app.component('TooltipContent', TooltipContent);
  app.component('TooltipProvider', TooltipProvider);
  app.component('TooltipTrigger', TooltipTrigger);
}
